app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import current_user,UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    hashed_password = db.Column(db.String(255))
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255),nullable = False)
    content = db.Column(db.Text(), nullable = False)
    category = db.Column(db.String(255), index = True,nullable = False)

    def save_p(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'Pitch {self.post}'

class Quote:

    def __init__(self,quote,author):
        self.quote = quote
        self.author = author

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    post_id = db.Column(db.Integer)
    post_title = db.Column(db.String)
    post_comment = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE


simple = SimpleMDE()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
db = SQLAlchemy()
bootstrap = Bootstrap()
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    # configure UploadSet
    configure_uploads(app,photos)



    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from .views import *

app/main/views.py
from flask import render_template,request,redirect,url_for, abort
from . import main
from ..models import User, Post
from .. import db,photos
from ..requests import get_quotes
from flask_login import login_required, current_user
from .forms import UpdateProfile
import markdown2
import os

# @main.route('/')
# def index():
#
#     random_quotes = get_quotes()
#     print(random_quotes)
#
#     return render_template('index.html', random_quotes = random_quotes )

# Views
@main.route('/', methods = ['GET','POST'])
def index():

    # quotes = get_quotes()
    users = User.query.all()
    posts = Post.query.all()


    # random_quotes = get_quotes()
    # print(random_quotes)

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to Aenshtyns Blog'
    return render_template('index.html', title = title, users = users, posts = posts  )

    # return render_template('index.html', title = title, random_quotes = random_quotes, users = users, posts = posts)


@main.route('/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_post(id):

       return render_template('new_blog.html',title = title)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comment/<int:id>')
def single_comment(id):
    comment=Comment.query.get(id)
    if comment is None:
        abort(404)
    format_comment = markdown2.markdown(comment.movie_comment,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('comment.html',comment = comment,format_comment=format_comment)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}

{% block content%}
<div class="container-fluid">

  <div class="row">
    <div class="col-sm-4">
      <img src="{{comment.image_path}}" class="img-responsive">
    </div>

    <div class="col-sm-8">
      {{format_comment|safe}}
    </div>
  </div>
</div>
{%endblock%}

app/templates/error.html
{% extends 'base.html'%}

{% block content %}
   <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}


<!-- Content block -->
{% block content %}



{{ macro.display(posts) }}

{% endblock%}

app/templates/macros.html
{% macro display(posts) %}

{% for post in posts %}

 <li>{{ post.category}}</li>
  <li>{{ post.title }}</li>
 <li>{{ post.content }}</li>


{% endfor %}

{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Blogs </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>

                      <li><a href="{{url_for('auth.register')}}">Sign Up</a></li>

                    {%endif%}
                  </ul>
        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div  i="particles-js"  >
        <div class=" row" >

            <div class="col-md-2"></div>
            <div class="col-md-8" id="postform">
                <h2 class="text-center">Create Your Blog Here!</h2>
                {{wtf.quick_form(form)}}
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

{% endblock%}

app/templates/new_comment.html
<div class="col-md-4">
        {{ wtf.quick_form(review_form) }}
        {{simplemde.load}}
    </div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
     {% if user.profile_pic_path %}

     <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

     {%else%}
     <p>No profile picture</p>

     {% endif %}

         {% if user == current_user %}
     <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

       <input type="file"  name="photo" class="form-control" required>
       <input type="submit">
     </form>
       {% endif %}
   </div>

   
  {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}